---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    install_apt:
      - net-tools
    remove_apt: []
    install_snap: []
    remove_snap: []
  roles:
    - install
    - uninstall
    - rclocal