---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    install_apt:
      - git
      - lxc
      - lxc-templates
      - python3-lxc
      - net-tools
      - sysstat
      - fio
      - mdadm
      - cryptsetup
      - dnsmasq
    remove_apt: []
    install_snap: []
    remove_snap:
      - lxd
    encrypted: yes
    eth1: "{{ ansible_eth1.ipv4.address }}/{{ ansible_eth1.ipv4.netmask }}"
    eth2: "{{ ansible_eth2.ipv4.address }}/{{ ansible_eth2.ipv4.netmask }}"
    eth3: "{{ ansible_eth3.ipv4.address }}/{{ ansible_eth3.ipv4.netmask }}"
    eth4: "{{ ansible_eth4.ipv4.address }}/{{ ansible_eth4.ipv4.netmask }}"
    eth5: "{{ ansible_eth5.ipv4.address }}/{{ ansible_eth5.ipv4.netmask }}"
    eth6: "{{ ansible_eth6.ipv4.address }}/{{ ansible_eth6.ipv4.netmask }}"
  roles:
    - install
    - uninstall
    - rclocal
    - las32_v3_raid0
    - dnsmasq
    - fusion