---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    install_apt:
      - git
      - lxc
      - lxc-templates
      - python3-lxc
      - net-tools
      - sysstat
      - fio
      - mdadm
      - cryptsetup
      - dnsmasq
    remove_apt: []
    install_snap: []
    remove_snap:
      - lxd
    encrypted: yes
  roles:
    - install
    - uninstall
    - rclocal
    - las32_v3_raid0
    - dnsmasq
    - fusion