---
- name: Relink the /var/lib/lxc directory to the /containers mountpoint
  file:
    src: /containers
    dest: /var/lib/lxc
    force: yes
    state: link

- name: Empty lxc defaults file
  shell: cat /dev/null > /etc/lxc/default.conf
  args:
    executable: /bin/bash

- name: Create a started container
  lxc_container:
    name: test-ubuntu
    backing_store: loop
    fs_size: 40G
    fs_type: xfs
    container_log: true
    state: started
    template: download
    template_options: --dist ubuntu --release focal --arch amd64
    container_command: |
      sleep 5
    container_config:
      - "lxc.apparmor.profile = unconfined"
      - "lxc.net.0.type=phys"
      - "lxc.net.0.link=eth1"
      - "lxc.net.0.name=eth0"
      - "lxc.net.0.flags=up"
      - "lxc.net.0.ipv4.address={{ eth1 | ansible.utils.ipaddr('network/prefix') }}"
      - "lxc.mount.entry = /data data none bind,create=dir 0 0"

- name: Run startup commands on container
  lxc_container:
    name: test-ubuntu
    container_command: |
      date 2>&1 | tee -a /var/log/container-init.log
      sleep 5 #Wait for network interfaces to fully come up
      ip route add default via 10.0.2.1 && ip route | tee -a /var/log/container-init.log
      echo "DNS={{ ansible_eth0.ipv4.address  }}" >>/etc/systemd/resolved.conf 2>&1 | tee -a /var/log/container-init.log
      systemctl restart systemd-resolved | tee -a /var/log/container-init.log
      apt-get update 2>&1 | tee -a /var/log/container-init.log
      apt-get install -y git ansible 2>&1 | tee -a /var/log/container-init.log
      git clone https://github.com/burgerjx/iog-hpcc-vmboot.git /opt/ansible 2>&1 | tee -a /var/log/container-init.log
      ansible-playbook /opt/ansible/container-ubuntu20.yml 2>&1 | tee -a /var/log/container-init.log