---
- name: Relink the /var/lib/lxc directory to the /containers mountpoint
  file:
    src: /containers
    dest: /var/lib/lxc
    force: yes
    state: link

- name: Create a started container
  lxc_container:
    name: test-ubuntu
    backing_store: loop
    fs_size: 40G
    fs_type: xfs
    container_log: true
    state: started
    template: download
    template_options: --dist ubuntu --release focal --arch amd64
    container_config:
      - "lxc.apparmor.profile = unconfined"
      - "lxc.net.1.type=phys"
      - "lxc.net.1.link=eth1"
      - "lxc.net.1.flags=up"
      - "lxc.net.1.ipv4.address=10.0.1.4/24"
      - "lxc.mount.entry = /nvme nvme none bind,create=dir 0 0"